- name: Check prerequisite packages are installed
  hosts: k3s_initial_master:k3s_master:k3s_worker:!localhost
  become: true
  tasks:
    - package:
        name: [wireguard, nfs-common]
        state: present
        update_cache: true
        cache_valid_time: 3600

- name: Setup initial k3s master node
  hosts: k3s_initial_master:!localhost
  become: true
  roles:
    - swap
    - k3s-initial-master

- name: Setup other k3s master nodes
  hosts: k3s_master:!localhost
  become: true
  roles:
    - swap
    - k3s-master

- name: Setup k3s worker nodes
  hosts: k3s_worker:!localhost
  become: true
  roles:
    - swap
    - k3s-worker
