- name: Setup k3s load balancer
  hosts: k3s_load_balancer:!localhost
  become: true
  roles:
    - k3s-load-balancer

- name: Use wireguard as flannel backend
  hosts: k3s_initial_master:k3s_master:k3s_worker:!localhost
  become: true
  tasks:
    - name: Check wireguard is installed
      package:
        name: wireguard
        state: present
        update_cache: true
        cache_valid_time: 3600

- name: Setup initial k3s master node
  hosts: k3s_initial_master:!localhost
  become: true
  roles:
    - swap
    - k3s-initial-master

- name: Setup other k3s master nodes
  hosts: k3s_master:!localhost
  become: true
  roles:
    - swap
    - k3s-master

- name: Setup k3s worker nodes
  hosts: k3s_worker:!localhost
  become: true
  roles:
    - swap
    - k3s-worker
