- name: Master playbook
  hosts: all:!localhost
  become: true
  roles:
    - swap
    - caddy
    - watchtower
    - bitwarden
    - pihole
    - grafana
    - nextcloud
    - minecraft
    - plex
    - tautulli
