- name: Set variables
  set_fact:
    firewalld_services: "{{ firewalld_services }}"

- name: Check nginx is installed
  package:
    name: nginx
    state: present
    update_cache: yes

- name: Setup firewall
  include_role:
    role: firewalld

- name: Get letsencrypt certs
  include_role:
    role: letsencrypt

- name: Remove default file
  file:
    path: "/etc/nginx/sites-enabled/default"
    state: absent

- name: Template nginx configuration file
  copy:
    src: "{{ nginx_conf_file }}"
    dest: "/etc/nginx/nginx.conf"
  register: nginx_conf

- name: Check nginx site configuration
  template:
    src: "{{ nginx_template_file }}"
    dest: "/etc/nginx/sites-available/{{ hostname }}"
  register: nginx_template

- name: Ensure nginx site symlink
  file:
    src: "/etc/nginx/sites-available/{{ hostname }}"
    dest: "/etc/nginx/sites-enabled/{{ hostname }}"
    state: link
  register: nginx_symlink

- name: Restart nginx
  service:
    name: nginx
    state: restarted
    enabled: yes
  when: >
    nginx_template.changed or
    nginx_symlink.changed or
    nginx_conf.changed
