- name: Check nginx is installed
  package:
    name: nginx
    state: present
    update_cache: yes
    cache_valid_time: 3600

- name: Setup firewall
  include_role:
    role: firewalld
  vars:
    firewalld_services: ["http", "https"]

# [DEPRECATED] moved to caddy
# - name: Get letsencrypt certs
#   include_role:
#     role: letsencrypt

- name: Remove default file
  file:
    path: "/etc/nginx/sites-enabled/default"
    state: absent

- name: Template nginx configuration file
  copy:
    src: "nginx.conf"
    dest: "/etc/nginx/nginx.conf"
  register: nginx_conf

# [DEPRECATED] moved to caddy
# - name: Check nginx site configuration
#   template:
#     src: "{{ nginx_template_file }}.j2"
#     dest: "/etc/nginx/sites-available/{{ hostname }}"
#   register: nginx_template

# - name: Ensure nginx site symlink
#   file:
#     src: "/etc/nginx/sites-available/{{ hostname }}"
#     dest: "/etc/nginx/sites-enabled/{{ hostname }}"
#     state: link
#   register: nginx_symlink

- name: Ensure nginx stream configuration
  block:
    - file:
        path: "/etc/nginx/streams/"
        state: directory
    - template:
        src: "{{ nginx_stream_file }}.j2"
        dest: "/etc/nginx/streams/{{ nginx_stream_file }}"
      register: nginx_stream
  when: nginx_stream_file is defined

- name: Restart nginx
  service:
    name: nginx
    state: restarted
    enabled: yes
  when: >
    nginx_stream is defined and nginx_stream.changed or
    nginx_conf.changed
