- name: Bitwarden container present
  docker_container:
    name: bitwarden
    image: bitwardenrs/server
    restart_policy: unless-stopped
    ports:
      - "3011:80"
      - "3012:3012"
    volumes:
      - "/data/bitwarden/:/data/"
    env:
      DOMAIN: "https://vault.{{ domain }}"

- name: Setup bitwarden nginx conf
  include_role:
    name: nginx
  vars:
    hostname: "vault.{{ domain }}"
    nginx_template_file: "vault"
