- name: Add certbot repository
  apt_repository:
    repo: 'ppa:certbot/certbot'

- name: Install certbot's nginx package
  package:
    name: python-certbot-nginx
    state: present
    update_cache: true
    cache_valid_time: 3600

- name: Check domain certificate
  stat:
    path: "/etc/letsencrypt/live/{{ hostname }}/cert.pem"
  register: cert

- name: Generate new certificate for domain if one doesn't exist.
  shell: "certbot certonly --nginx --noninteractive --agree-tos --email {{ certbot_admin_email }} -d {{ hostname }}"
  when: not cert.stat.exists
