- name: Check swap file
  become: yes
  block:
  - name: Check if swap file exists
    stat:
      path: "{{swap_file}}"
    register: swap_file_check

  - name: Create swap file
    become: yes
    command: fallocate -l {{swap_size}} {{swap_file}}
    when: not swap_file_check.stat.exists

  - name: Change swap file permissions
    become: yes
    file: path="{{swap_file}}"
          owner=root
          group=root
          mode=0600

  - name: Format swap file
    become: yes
    command: "mkswap {{swap_file}}"
    when: not swap_file_check.stat.exists

  - name: Write swap entry in fstab
    become: yes
    mount: name=none
           src={{swap_file}}
           fstype=swap
           opts=sw
           passno=0
           dump=0
           state=present

  - name: Turn on swap
    become: yes
    command: swapon -a
    when: not swap_file_check.stat.exists

  - name: Set swappiness
    become: yes
    sysctl:
      name: vm.swappiness
      value: "{{swappiness}}"
