- name: Check docker and pip is installed
  package:
    name: [docker.io, python3-pip]
    state: present
    update_cache: yes

- name: Install docker module for python
  pip:
    name: docker

- name: Ensure docker service is started and enabled
  service:
    name: docker
    state: started
    enabled: yes
