- name: Setup grafana dashboard
  import_tasks: dashboards.yml

- name: Grafana container present
  docker_container:
    name: grafana
    image: grafana/grafana
    user: root
    restart_policy: unless-stopped
    network_mode: host
    volumes:
      - "/data/grafana/:/var/lib/grafana"
    env:
      GF_AUTH_HIDE_LOGIN_FORM: "{{ gf_auth.hide_login_form }}"
      GF_AUTH_ANONYMOUS_ENABLED: "{{ gf_auth.anonymous_enabled }}"
      GF_AUTH_ANONYMOUS_ORG_ROLE: "{{ gf_auth.anonymous_org_role }}"
      GF_ALERTING_ENABLED: " {{ gf_alerting.enabled }}"
      GF_PATHS_PROVISIONING: "/var/lib/grafana/provisioning"
  register: grafana_container
  notify:
    - Generate grafana password
    - Set grafana password
    - Print grafana password
    - Add prometheus datasource
    - Set preferred home dashboard

- name: Setup caddy for grafana
  include_role:
    name: caddy
  vars:
    caddyfile_marker: "# {mark} ANSIBLE Grafana"
    caddyfile_block: |
      monitor.{{ domain }} {
        reverse_proxy localhost:3000
      }
