- name: Install dependencies
  become: yes
  package:
    name: [git, wireguard, cargo, libclang-dev, libsqlite3-dev]
    state: present
    update_cache: true
    cache_valid_time: 3600

- name: Check if innernet has been installed
  stat:
    path: /usr/bin/innernet-server
  register: result

- name:
  set_fact:
    innernet_exists: "{{ result.stat.exists }}"
  changed_when: false

- name: Install innernet
  block:
  - name: Clone git repo
    git:
      repo: "https://github.com/tonarino/innernet"
      dest: innernet/
      version: "{{ innernet_version }}"

  - name: Install cargo-deb
    shell: cargo install cargo-deb

  - name: Build and install server deb package
    shell: cargo deb --install -p server
    args:
      chdir: innernet/
      creates: "usr/bin/innernet-server"
  when: not innernet_exists

- name: Clean up post-installation
  file:
    state: absent
    path: innernet/
