- name: Set pihole privacy level
  lineinfile:
    path: "/data/pihole/etc-pihole/pihole-FTL.conf"
    regexp: "^PRIVACYLEVEL="
    line: "PRIVACYLEVEL={{ pihole_privacy_lvl }}"
    create: true

- name: Set pihole logging level
  command: docker exec -it pihole bash -c "pihole logging {{ pihole_logging }}"

- name: Generate pihole password
  set_fact:
    pihole_password: "{{ lookup('password', '/dev/null length=16 chars=ascii_letters') }}"

- name: Set pihole password
  shell: "docker exec pihole pihole -a -p {{ pihole_password }}"

- name: Print pihole password
  debug:
    msg: "Pihole password: {{ pihole_password }}"
  changed_when: true
