- name: Setup DNS
  import_tasks: dns.yml

- name: Pihole container present
  docker_container:
    name: pihole
    image: pihole/pihole
    restart_policy: unless-stopped
    ports:
      - "31415:80"
      - "53:53/tcp"
      - "53:53/udp"
    volumes:
      - "/data/pihole/etc-pihole/:/etc/pihole/"
      - "/data/pihole/etc-dnsmasq.d/:/etc/dnsmasq.d/"
    dns_servers: [127.0.0.1, 1.1.1.1]
    env:
      TZ: "America/Los_Angeles"
      DNS1: "1.1.1.1"
      DNS2: "1.0.0.1"
      DNSSEC: "True"
  register: pihole_container

- name: Set pihole privacy level
  lineinfile:
    path: "/data/pihole/etc-pihole/pihole-FTL.conf"
    regexp: "^PRIVACYLEVEL="
    line: "PRIVACYLEVEL={{ pihole_privacy_lvl }}"
    create: "yes"
  when: pihole_container.changed

- name: Set pihole logging level
  command: docker exec -it pihole bash -c "pihole logging {{ pihole_logging }}"
  when: pihole_container.changed

- name: Generate pihole password
  set_fact:
    pihole_password: "{{ lookup('password', '/dev/null length=16 chars=ascii_letters') }}"
  when: pihole_container.changed

- name: Set pihole password
  shell: "docker exec pihole pihole -a -p {{ pihole_password }}"
  when: pihole_container.changed

- debug:
    msg: "Pihole password: {{ pihole_password }}"
  changed_when: true
  when: pihole_container.changed

- name: Setup pihole nginx conf
  include_role:
    name: nginx
  vars:
    hostname: "dns.{{ domain }}"
    nginx_template_file: "dns"
    nginx_stream_file: "dns-over-tls"
    firewalld_services: ["dns"]
    firewalld_ports: ["853/tcp"]
