- name: Create prometheus directory
  file:
    path: /data/prometheus
    state: directory

- name: Check prometheus config
  copy:
    src: "prometheus.yml"
    dest: "/data/prometheus/prometheus.yml"

- name: Prometheus container present
  docker_container:
    name: prometheus
    image: prom/prometheus
    user: root
    restart_policy: unless-stopped
    network_mode: host
    volumes:
      - "/data/prometheus:/prometheus"
    command:
      - '--config.file=/prometheus/prometheus.yml'
      - '--storage.tsdb.retention.time=100y'
      - '--storage.tsdb.retention.size=20GB'

- name: Check exporters
  include_tasks: "{{ item }}.yml"
  loop: "{{ prometheus_exporters }}"
