- name: Minecraft container present
  docker_container:
    name: mc
    image: itzg/minecraft-server
    restart_policy: unless-stopped
    ports:
      - "25565:25565"
      - "8123:8123" # Dynmap
      - "8804:8804" # Player Analytics
    volumes:
      - "/data/mc/:/data/"
    env:
      EULA: "TRUE"
      TYPE: "PAPER"
      VERSION: "LATEST"
      MEMORY: "3G"
    command:
      # Some older versions (pre-1.14) of Spigot require this when detaching stdin
      - "--noconsole"
