- name: Check firewalld is installed
  package:
    name: firewalld
    state: present

- name: Open service ports
  loop: "{{ firewalld_services }}"
  firewalld:
    service: "{{ item }}"
    permanent: yes
    state: enabled

- name: Open ports
  loop: "{{ firewalld_ports }}"
  firewalld:
    port: "{{ item }}"
    permanent: yes
    state: enabled
