- name: Check firewalld is installed
  package:
    name: firewalld
    state: present
    update_cache: true
    cache_valid_time: 3600
  register: firewalld_installed

- name: Open service ports
  loop: "{{ firewalld_services }}"
  ansible.posix.firewalld:
    service: "{{ item }}"
    permanent: true
    state: enabled
  register: firewalld_services_changed

- name: Open ports
  loop: "{{ firewalld_ports }}"
  ansible.posix.firewalld:
    port: "{{ item }}"
    permanent: true
    state: enabled
  register: firewalld_ports_changed

- name: Restart firewalld
  service:
    name: firewalld
    state: restarted
    enabled: true
  when: firewalld_installed.changed or firewalld_services_changed.changed or firewalld_ports_changed.changed
  register: firewalld_restarted

- name: Populate service facts
  service_facts:

- name: Restart docker after restarting firewalld
  service:
    name: docker
    state: restarted
    enabled: true
  when: firewalld_restarted.changed and 'docker.service' in services
