- name: Check firewalld is installed
  package:
    name: firewalld
    state: present
    update_cache: yes
    cache_valid_time: 3600
  register: firewalld_installed

- name: Open service ports
  loop: "{{ firewalld_services }}"
  firewalld:
    service: "{{ item }}"
    permanent: yes
    state: enabled
  register: firewalld_services_changed

- name: Open ports
  loop: "{{ firewalld_ports }}"
  firewalld:
    port: "{{ item }}"
    permanent: yes
    state: enabled
  register: firewalld_ports_changed

- name: Restart firewalld
  service:
    name: firewalld
    state: restarted
    enabled: yes
  when: firewalld_installed.changed or firewalld_services_changed.changed or firewalld_ports_changed.changed
